server:
  port: 8080

spring:

  kafka:
    bootstrap-servers: 10.1.209.95:9092
    consumer:
      group-id: group-id

  application:
    name: com-intelixcloudmessenger-ws

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 0


