server:
  port: 8080

spring:

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/TEST
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1;
      connection-timeout: 20000

  application:
    name: java-springboot-jdbc

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB


